<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body style="background-image: url('/images/main.png')">
<a href="/queryUsers" target="right" class="btn btn-info" style="margin: 15px 50px">用户信息</a><br>
<a href="/queryEmployees" target="right" class="btn btn-info" style="margin: 15px 50px">员工信息</a><br>
<a href="/queryGoods" target="right" class="btn btn-info" style="margin: 15px 50px">商品信息</a><br>
<a href="/queryPurchases" target="right" class="btn btn-info" style="margin: 15px 50px">入库信息</a><br>
<a href="/querySell" target="right" class="btn btn-info" style="margin: 15px 50px">出库信息</a><br>
<a href="/querySupplys" target="right" class="btn btn-info" style="margin: 15px 50px">供货信息</a><br>
<a href="/" target="_top" class="btn btn-info" style="margin: 15px 50px">退出系统</a><br>
<link rel="stylesheet" href="/bootstrap-4.5.0-dist/css/bootstrap.min.css">
<script src="/js/jquery-3.4.1.min.js"></script>
</body>
</html>